name: optimization_algorithms
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scikit-opt>=0.6
  - tqdm>=4.60.0
  - pip
  - kagglehub>=0.3.13
  - ipykernel
  - pip:
    - -r requirements.txt
